// packages/template-vue-tailwindcss/src/views/Home/components/StoreTest.vue
<script setup lang="ts">
import { useCounterStore } from '@/stores/counter.ts'
const counterStore = useCounterStore()
</script>

<template>
  <div class="flex flex-col items-center gap-20 bg-base-100 py-20">
    <div class="mockup-phone">
      <div class="camera" />
      <div class="display">
        <div class="phone-1 artboard artboard-demo">
          <p class="text-xl font-medium tracking-wide uppercase">Counter:</p>
          <p class="text-4xl font-bold uppercase">
            {{ counterStore.count }}
          </p>
          <button type="button" class="btn btn-primary" @click="counterStore.increment()">
            increment
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// packages/template-react-tailwindcss/src/pages/Home/components/StoreTest.tsx
import { useState } from "react";

const StoreTest = () => {
    const [count, setCount] = useState(0);
    return (
        <div className="flex flex-col items-center gap-20 bg-base-100 py-20">
            <div className="mockup-phone">
                <div className="camera" />
                <div className="display">
                    <div className="phone-1 artboard artboard-demo">
                        <p className="text-xl font-medium tracking-wide uppercase">Counter:</p>
                        <p className="text-4xl font-bold uppercase">{count}</p>
                        <button type="button" className="btn btn-primary" onClick={() => setCount(count + 1)}>
                            increment
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};
export { StoreTest };
